### PR TITLE
feat(groupBy): implement core groupBy logic

### LINKED ISSUE #670: groupBy support
This isn't so much a feature request as much as it is an offer to take a crack at implementing it, as it would be super useful for my team.  Obviously groupBy is pretty complex, but are there any pitfalls besides that?

### PR DESCRIPTION
**Pull request by ThatJoeMoore**
* Fixes #670 

Okay.  This doesn't have `skip`, `take`, or `cursor` supported yet, but the core `groupBy` (including `where`, `having`, `orderBy`) is working and passing the tests I came up with. Gonna take another pass at this to clean up the code and add comments and such, but hey, here's a WIP version!

In addition, and I will separate this out into its own PR, I added support for the `_count: true` shorthand in aggregation.

For the most part, the code here is just data transformations to be able to use the existing functions with little or no modification.  A lot of that is because the argument structures for groupBy are different (looking at you, all of nested aggregate stuff), so it made more sense to have groupBy adapt to the other functions than to have them be able to support groupBy.

The core part of this is `divideIntoGroups`, which takes the specified `by` values and iterates over the data items, using `pick` and `shallowCompare` to put them into a group.  As part of this, it pre-computes the values each group needs to run `orderBy` and `having` checks, so as to simplify the implementations of those functions later (as well as, maybe making them a teensy bit more efficient).

Anyway, like I said, I'm gonna clean up and document the code here and revert a bunch of the formatting changes my editor decided to make, but you can take a look at what I've got so far.

### CODE REVIEW

**Comment by ThatJoeMoore** [comment]
Oh, also, I should note that I've only tested on Postgres so far, but I'll test it on the other backends soon.

**Comment by morintd** [comment]
Hello @ThatJoeMoore , the good news is there is a single failing test with MongoDB. We cannot use raw/number ids as they're different with Mongo, instead we have to find the related user with a query and use its id directly `realUser.id`/`mockUser.id`.

I won't be able to fix it myself before next week, feel free to do so if you are available or I'll try to do so as soon as possible.

Thanks again for participating 🙏

**Comment by ludalex** [comment]
How can I test this locally within my project?

Adding the dependancy as ```"prismock": "github:ThatJoeMoore/prismock#4b0115ec10ca73e4b91483bab91aaa202d6b037e"``` works but it's missing the `dist/` folder.

**Comment by morintd** [comment]
Hello @ludalex , I've had issues with linking and using Prismock in another local project, so I won't have a solution in the short-term.

**Pull request merged**
