### PR TITLE
feat: 🧑‍💻 delegates raise PrismaClientKnownRequestError

### PR DESCRIPTION
**Pull request by paulsouche**
This pull request covers some cases of the #1082 

It is not perfect. It covers only `P2025` error codes and the error messages are not the same than the prisma exceptions. As they have some legacy errors, I did not take this into consideration.

It introduces a breaking change on `update` as it will now raise an exception instead of returning `null` 

That's a start. I will have a look if we can easily improve these error messages. Meanwhile, let me know what you think :pray:

### CODE REVIEW

**Comment by thw0rted** [comment]
@morintd could you please take a look at this?  I believe it would fix a lot of tests that we currently have to skip because they expect the Prisma call to throw on missing records.

**Comment by paulsouche** [comment]
@thw0rted have you seen my workaround in [#1082](https://github.com/morintd/prismock/issues/1082#issuecomment-2395205263) ?

**Comment by thw0rted** [comment]
Yes, thanks @paulsouche -- I'm going to look at adding that, but after posting the above comment I realized that some of my `findUniqueOrThrow` calls do throw (just "new Error()", not the more-accurate version from this PR) while some return null instead of throwing.  I haven't had a chance to investigate why this is.  I probably need to figure out what's going on there first; if I'm actually hitting another bug I'll try to boil it down to a simple repro...

**Comment by morintd** [comment]
Hello @paulsouche , thanks a lot for your work. Sorry for the delay, this PR has finally been merged 🙏

**Pull request merged**
